common:
    lid_topic:  "/livox/lidar"
    repub_topic:  "/livox/lidar_repub"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    rootDir: "/workspace/catkin_ws/result/"
    savePCD: true                         # https://github.com/TixiaoShan/LIO-SAM/issues/3
    savePCDDirectory: "PCDs/"        
    saveSCD: true 
    saveSCDDirectory: "SCDs/"
    saveLOG: true
    saveLOGDirectory: "LOG/"
    map_save_en: true  # global map
    pcd_save_interval: 1                 # how many LiDAR frames saved in each pcd
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR
    livox_type: 3
    scan_line:  6
    blind: 0.2
                      
mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:   360 
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    map_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

loop:
    loopClosureEnableFlag: true 
    loopClosureFrequency: 1.0
    historyKeyframeSearchRadius: 10.0
    historyKeyframeSearchTimeDiff: 30.0
    historyKeyframeSearchNum: 1  # submap
    historyKeyframeFitnessScore: 0.2